### ISSUE TITLE
Is multi host openmpi supported?

### ISSUE THREAD

**Issue by rcplane** [oweidner/docker.openmpi#5]
Hello, I have an interest in running mpi across multiple Docker Engine hosts/VMs/instances in a cloud and I am wondering if you have tried such a setup using a variant on this container?

**Comment by oweidner** [comment]
Hi, yes I have actually used the MPI containers across multiple hosts. I have used Rancher (http://rancher.com) as a container / host orchestrator. Rancher provides a virtual networking layer across containers and hosts - that makes things pretty simple. 

Kubernetes is another good option for container orchestration, but I found Rancher easier to deploy and get started with.

**Comment by rcplane** [comment]
Interesting, thank you for the suggestions.  I should note that I was trying out a setup using docker.openmpi based container images run as Docker Swarm services similar to https://github.com/NLKNguyen/alpine-mpich cluster setup and also recently had success running mpi commands across multiple hosts.
